### ISSUE TITLE
Please add the `Auto Complete` feature.

### ISSUE THREAD

**Issue by SHUBHAMR69** [AyProductions-Team/NEXT#10]
An autocomplete feature like the one in JAVA N-IDE would be useful.

Here is the content of a message by me to @AyProductions .

> @SHUBHAMR69 

But the best feature which can make your app the best is `autocomplete`.
Not the one like in `AndroidStudio`, but like the one in `JAVA N-IDE` (The android Java IDE which I've used till now.)

Every beginner can learn too many things through that awesome autocomplete feature. Believe me I learned most of Java due to that.

If you want to know what happens in that, then here it is : 

* Whenever you type a part of a word or start typing it, you'll see a popup box containing all available class names or keywords. The containing package is also shown for classes.
* Whenever you type a `.` after a class name or its object, all the `visible` methods and variables in that class, including method return type, parameters, variable's data type are shown.
* Whenever a class is selected from the list, it is automatically imported in the program, thus saving time.

It can help people learn in this way : 

* People will know about Classes and methods which they didn't know before, while finding the method they wanted to autocomplete. And method names are mostly quite meaningful, causing some to find out some method which was previously in a library. Later, they'd search up the purpose of each class. <br><br> I've learned about 100s of classes and methods through this.

* Sometimes, wanting to learn easily about required functions, people can just open up the IDE and type a character, e.g. `A`, so they'll know all classes starting with `A`, and they can simply web search about the required class. (This is what I used to do in my free time.)

I'd recommend you to once check out JAVA N-IDE's autocomplete feature. JAVA N-IDE is available on PlayStore. <br><br>

**Comment by AyProductions** [comment]
Working on it!!

**Comment by AyProductions** [comment]
Please post me screenshot of JAVA N-IDE. I checked the wrong IDE.

**Comment by AyProductions** [comment]
Added it!!
